### PR TITLE
math: a more general floating point trait

### PR DESCRIPTION
**Pull request by aelkazdadi**

### CODE REVIEW

**Review by jcarpent — APPROVED** [review]
Nice fix. Thanks a lot for your contribution @aelkazdadi.

**Review by jcarpent — COMMENTED** [review]
@aelkazdadi Do you know why the compilation is failing?

**Comment by aelkazdadi** [comment]
```cpp
    template<typename Scalar> \
    Scalar name(const Scalar & value) \
    { using std::name; return name(value); }
```
it's a case where `Scalar` is an expression. 
```
expression<
  boost::multiprecision::detail::subtract_immediates,
  boost::multiprecision::number<
    boost::multiprecision::backends::cpp_dec_float<100>
  >,
  boost::multiprecision::number<
    boost::multiprecision::backends::cpp_dec_float<100>
  >
  ,[...]
  ,[...]
>
```
passing it through `fabs` produces another expression, which needs to be cast to the owning type `number<...>`

**Comment by jcarpent** [comment]
Could provide an explicit cast?

**Comment by jcarpent** [comment]
@aelkazdadi I've pushed the change we've discussed so far.

**Pull request merged**
