### PR TITLE
Handle SRDF file parsing for activation of collision pairs

### PR DESCRIPTION
**Pull request by jcarpent**
A dedicated unit test is coming soon.

### CODE REVIEW

**Comment by nmansard** [comment]
The parsing code should be moved outside the class. I suggest to add a file src/multibody/parser/srdf.hpp.

**Comment by jcarpent** [comment]
I think what you mentioned needs more justifications. Just because you do not build a Geometry Data from a SRDF file. You just remove some collision pairs between supporting links.

**Comment by nmansard** [comment]
SRDF is only one convention to store a part of the model. A direct dependency on this specific convention should not be added directly in the model header. 

Decoupling the C++ representation of the model and the serialization to text/bin file is a good procedure, that we already applied for the URDF  parser. I simply suggest here to do the same for SRDF.

**Comment by jcarpent** [comment]
I do agree with the first statement. 
The idea is really to avoid the creation of too many algorithms that are not strictly algorithms, just parsers that need to be called after the creation of the GeometryData entity for example. Maybe, we need to define a proper way to deal with such constraints:
- readable code
- also easy to use

**Pull request merged**
