### PR TITLE
Fix method play() of rviz_visualizer

### PR DESCRIPTION
**Pull request by danielcostanzi18**
Method `play()` overridden, `Qtest.qWait()` used for the delay between one display to another instead of `time.sleep()`.
In the original implementation method `play()` form base_visualizer was used.

### CODE REVIEW

**Comment by hrp2-14** [comment]
Hi ! This project doesn't usually accept pull requests on master.
If this wasn't intentionnal, you can change the base branch of this PR to devel
(No need to close it for that). Best, a bot.

**Comment by jcarpent** [comment]
Thanks @danielcostanzi18 for your contribution.
I made a slight modifications.

**Review by jcarpent — APPROVED** [review]

**Comment by nim65s** [comment]
Please follow the dry principle (Don't Repeat Yourself).
Instead of copy/pasting the whole `play` method, you can define the `def sleep(self, dt)` method in the base class, with `time.sleep(dt)` in the base case, and call that instead of `time.sleep(dt)` in the `play` method.
Then, in the RViz derived class, all you have to do is to define another `def sleep(self, dt)` method with the required `qWait(dt * 1000)` instead

**Comment by jcarpent** [comment]
@danielcostanzi18 COuld you handle the change requested by @nim65s?

**Pull request merged**
