### PR TITLE
Implement Hessian of the kinematics

### PR DESCRIPTION
**Pull request by jcarpent**
This is related to discussions in #867.

### CODE REVIEW

**Comment by jcarpent** [comment]
@markusgft I've implemented a first draft of the Hessian of the kinematics. It is only in C++ and I need to update EigenPy to handle Eigen::Tensor module. 
Do you need it rapidly?

**Comment by jcarpent** [comment]
@markusgft By the way, would you mind if this feature is only accessible in C++11 and more?

**Comment by gabrielebndn** [comment]
It seems compilation fails on 16.04 because of a `constexpr` in Eigen.
I am wondering, is it wise to use `unsupported` features of Eigen so deep in Pinocchio? Is it wise to #include it in Data? Wouldn't it be better to isolate these things in a separate part of Pinocchio?

**Comment by jcarpent** [comment]
@gabrielebndn This is because Eigen::Tensor relies on C++11. I have two solutions:
- make the code only existing in C++11 with an extra-macro to allow the inclusion of Eigen::Tensor
- make the code working for both C++98 and C++11, and then just copying the data inside an Eigen::VectorXd for alignment issues, and then providing some helper functions to treat them as Eigen::Tensor in C++11 through the Map.

**Comment by jcarpent** [comment]
The only thing is that I'm much more in favor of solution 1., because it will be much more compliant with the future of Pinocchio and most platforms, which will use C++11 compilation flag by default.

**Comment by jcarpent** [comment]
@gabrielebndn By the way, the naming unsupported used in Eigen is just because this is not the main feature of Eigen. But for sure, the Eigen::Tensor will remain supported for a while because it is at the heart of TensorFlow and PyTorch.

**Comment by gabrielebndn** [comment]
> @gabrielebndn This is because Eigen::Tensor relies on C++11. I have two solutions:
> 
> * make the code only existing in C++11 with an extra-macro to allow the inclusion of Eigen::Tensor
> * make the code working for both C++98 and C++11, and then just copying the data inside an Eigen::VectorXd for alignment issues, and then providing some helper functions to treat them as Eigen::Tensor in C++11 through the Map.

The first solution is much better, I agree.

**Comment by gabrielebndn** [comment]
> @gabrielebndn By the way, the naming unsupported used in Eigen is just because this is not the main feature of Eigen. But for sure, the Eigen::Tensor will remain supported for a while because it is at the heart of TensorFlow and PyTorch.

This was my main worry. Then I guess if TensorFlow is doing it, Pinocchio can too

**Comment by wxmerkt** [comment]
Thank you very much for providing this excellent feature! Since we just had a related conversation at Crocoddyl, my question is:

If this feature is only active when compiled with C++11, it won't be part of the robotpkg binaries, even for systems where C++11/14 is default? From the discussion at Crocoddyl it appears that "Pinocchio compiled with C++98 as distributed is incompatible with C++11 in a dependent project".

**Comment by cmastalli** [comment]
I am favor of option 1. After 18.04, we should forget about c++98, and together along c++11.

**Comment by markusgft** [comment]
> 
> 
> @markusgft I've implemented a first draft of the Hessian of the kinematics. It is only in C++ and I need to update EigenPy to handle Eigen::Tensor module.
> Do you need it rapidly?

Thank you @jcarpent for the update and implementing the feature! I think it is going to be very useful to a lot of people. As of now, I do not need the feature too rapidly, as I can also continue using the above mentioned workaround in the meantime. So please take your time!

Regarding the ensuing discussion: I do not know the deployment details and strategy of pinocchio, but I share the opinion that fixing C++11 as baseline requirement may be reasonnable.

**Comment by jcarpent** [comment]
@markusgft To update you, I finally implemented a minimal Tensor class (using snippets from Eigen). This should work on all the platforms now.

**Comment by jcarpent** [comment]
I will merge this PR as it is mature enough. I will provide other features soon.

**Pull request merged**
