### PR TITLE
[bindings/cppad] add pkg config dependency for pywrap when compiling with cppad

### PR DESCRIPTION
**Pull request by proyan**

### CODE REVIEW

**Comment by jcarpent** [comment]
Hi @proyan.
As far as I remember, this should not be required, because the Python bindings are not yet compatible with CppAD.

**Comment by proyan** [comment]
In case cppad is found by Pinocchio, the compilation of the files in the bindings directory would create an error because link to cppad is not provided by the pkg config.

If I remove this patch, I get the following error:

`cd pinocchio/build/bindings/python && /usr/bin/c++   -DPINOCCHIO_URDFDOM_TYPEDEF_SHARED_PTR -DPINOCCHIO_WITH_CPPADCG_SUPPORT -DPINOCCHIO_WITH_CPPAD_SUPPORT -DPINOCCHIO_WITH_HPP_FCL -DPINOCCHIO_WITH_URDFDOM -Dpinocchio_pywrap_EXPORTS -Ipinocchio/build -Ipinocchio/build/include -Ipinocchio/include -isystem /usr/include/python2.7 -isystem /local/rbudhira/devel/install/sot/include -isystem /usr/include/eigen3 -isystem /opt/ros/kinetic/include -isystem /usr/include/assimp  -pedantic -Wno-long-long -Wall -Wextra -Wcast-align -Wcast-qual -Wformat -Wwrite-strings -Wconversion  -fPIC   -isystem/usr/include/python2.7 -isystem/usr/lib/python2.7/dist-packages/numpy/core/include -DFCL_USE_ASSIMP_UNIFIED_HEADER_NAMES -DFCL_HAVE_OCTOMAP= -o CMakeFiles/pinocchio_pywrap.dir/spatial/expose-motion.cpp.o -c pinocchio/bindings/python/spatial/expose-motion.cpp
In file included from pinocchio/build/include/pinocchio/fwd.hpp:17:0,
                 from pinocchio/build/include/pinocchio/bindings/python/fwd.hpp:9,
                 from pinocchio/bindings/python/spatial/expose-motion.cpp:5:
pinocchio/build/include/pinocchio/math/cppad.hpp:20:29: fatal error: cppad/cppad.hpp: No such file or directory`

This patch is just meant to help the compilation.

**Comment by proyan** [comment]
pinocchio/bindings/python/spatial/expose-motion.cpp:5 would be the obvious choice from this error. However, there may be more.
I let you take care of it.

**Comment by jcarpent** [comment]
Do you have CppAD installed on your computer?

**Comment by jcarpent** [comment]
I did not encounter this issue under OSX, but I can now understand why you need it. 
I'm going to merge it now. Thanks for this report.

**Pull request merged**
