### PR TITLE
acknowledge the robocom++ fundings

### PR DESCRIPTION
**Pull request by nim65s**
Hi,

This PR acknowledges the fundings from robocom++, and especially @proyan's recent works, while paid by this project.

If there is any other preferred way to acknowledge a project, please let me know :)

### CODE REVIEW

**Comment by jcarpent** [comment]
In this spirit, a lot of projects are missing: ERC Leap (Inria), ERC Actanthrope, H2020 Memmo. @nim65s Could you add them too?

**Comment by nim65s** [comment]
Sure. Do you want a particular order ? Chronological or alphabetical ? With a distinction between national / european ?

**Comment by nim65s** [comment]
I didn't find a logo or a home page for the ERC Leap.

**Comment by jcarpent** [comment]
No, you can use the logo of the ERC, such as for Actanthrope. I think historical order is a good option.

**Comment by nim65s** [comment]
done :)

**Pull request merged**
