### PR TITLE
joints: fix return type of translation() or rotation() methods

### PR DESCRIPTION
**Pull request by jcarpent**
Related to #694.

### CODE REVIEW

**Comment by jcarpent** [comment]
@jmirabel This patch should fix your issue. Please let me know if it works.

**Comment by jcarpent** [comment]
To make this fix consistent with time, it would be necessary to provide some unit tests to check that compiles well. I don't have time to do it currently, but at least if this patch is working on your setup, this will be fine.

@jmirabel Can you provide a case where you are calling this method (translation()), because externally, this should not happen, except if you call a joint-generic.

**Comment by jmirabel** [comment]
I don't have time to fully validate it neither.

I did a small test. I don't think this change will fix the issue as the error is not on the constness but on the type itself.
```cpp
#include <Eigen/Core>

using namespace Eigen;

typedef typename Vector3d::ConstantReturnType LinearType;

// This does not work
// LinearType foo () { return LinearType::Zero (3); }
// This works
LinearType foo () { return LinearType::PlainObject::Zero (3); }

int main ()
{
  Vector3d v = foo();
}

```

**Comment by jcarpent** [comment]
Ok. I will set this case then.

**Comment by jcarpent** [comment]
I will merge it now. @jmirabel Thanks for this report, hoping it will be helpful but I'm not sure as it seems to be a bug from Eigen side.

**Pull request merged**
