### PR TITLE
Added some tolerance in testSINCOS()

### LINKED ISSUE #796: sincos unit test fails when compiled with clang-8.0
Build commands:
```bash
cd build
cmake .. -DCMAKE_CXX_COMPILER=/usr/bin/clang++ -DCMAKE_BUILD_TYPE=Release
make sincos
```

Run test:
```bash
unittest/sincos
```

Test output:
```
Running 1 test case...
/home/kotlyar/software/pinocchio/unittest/sincos.cpp(33): [1;31;49merror: in "sincosTest/test_sincos": check sin_value == sin_value_ref has failed[0;39;49m
/home/kotlyar/software/pinocchio/unittest/sincos.cpp(33): [1;31;49merror: in "sincosTest/test_sincos": check sin_value == sin_value_ref has failed[0;39;49m
...
"sincosTest/test_sincos": check sin_value == sin_value_ref has failed[0;39;49m
*** 1287 failures are detected in the test module "sincosTest
```

By changing `BOOST_CHECK` lines in the code to
```c++
    BOOST_CHECK_EQUAL(sin_value, sin_value_ref);
    BOOST_CHECK_EQUAL(cos_value, cos_value_ref);
```
I can see the values:
```
...
/home/kotlyar/software/pinocchio/unittest/sincos.cpp(25): error: in "sincosTest/test_sincos": check sin_value == sin_value_ref has failed [0.33331491171648064 != 0.3333149117164807]
/home/kotlyar/software/pinocchio/unittest/sincos.cpp(25): error: in "sincosTest/test_sincos": check sin_value == sin_value_ref has failed [0.81408624132169871 != 0.8140862413216986]
/home/kotlyar/software/pinocchio/unittest/sincos.cpp(25): error: in "sincosTest/test_sincos": check sin_value == sin_value_ref has failed [0.24940469018008196 != 0.24940469018008193]
/home/kotlyar/software/pinocchio/unittest/sincos.cpp(26): error: in "sincosTest/test_sincos": check cos_value == cos_value_ref has failed [0.95572248566259776 != 0.95572248566259765]
/home/kotlyar/software/pinocchio/unittest/sincos.cpp(26): error: in "sincosTest/test_sincos": check cos_value == cos_value_ref has failed [0.86869987885449307 != 0.86869987885449296]
/home/kotlyar/software/pinocchio/unittest/sincos.cpp(25): error: in "sincosTest/test_sincos": check sin_value == sin_value_ref has failed [0.5078055634522779 != 0.50780556345227801]
/home/kotlyar/software/pinocchio/unittest/sincos.cpp(26): error: in "sincosTest/test_sincos": check cos_value == cos_value_ref has failed [0.94032322684914449 != 0.9403232268491446]
/home/kotlyar/software/pinocchio/unittest/sincos.cpp(25): error: in "sincosTest/test_sincos": check sin_value == sin_value_ref has failed [0.36897122731672255 != 0.36897122731672249]
```
So the difference between the actual and the reference sin and cos values is very small but not 0.

Compiler version:
```
clang version 8.0.0-3 (tags/RELEASE_800/final)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

Exact compile command:
```bash
/usr/bin/clang++   -pedantic -Wno-long-long -Wall -Wextra -Wcast-align -Wcast-qual -Wformat -Wwrite-strings -Wconversion  -O3 -DNDEBUG  -rdynamic CMakeFiles/sincos.dir/sincos.cpp.o  -o sincos -Wl,-rpath,/home/kotlyar/software/pinocchio/build/src ../src/libpinocchio.so -lboost_unit_test_framework -lboost_filesystem -lboost_system -lboost_serialization -lurdfdom_sensor -lurdfdom_model_state -lurdfdom_model -lurdfdom_world -lconsole_bridge
```

CPU info: [cpuinfo.txt](https://github.com/stack-of-tasks/pinocchio/files/3184741/cpuinfo.txt)

With g++ as the compiler, the test passes.

### PR DESCRIPTION
**Pull request by mkatliar**
Fixes https://github.com/stack-of-tasks/pinocchio/issues/796

### CODE REVIEW

**Comment by jcarpent** [comment]
@mkatliar I made a minor change in your code to handle the near-zero case.
As soon as travis is done, I will merge it.

**Comment by jmirabel** [comment]
I think `tolerance` struct was added in boost 1.59. At least, I could not see it in the doc before 1.59. On 16.04, the default boost version is 1.58...

**Comment by jcarpent** [comment]
> I think `tolerance` struct was added in boost 1.59. At least, I could not see it in the doc before 1.59. On 16.04, the default boost version is 1.58...

Yes, I indeed realized that a bit late. I just decided to come back to the original proposition of @mkatliar.

**Comment by jmirabel** [comment]
That's good enough. I don't think this unit-test is of uttermost importance.

**Comment by gabrielebndn** [comment]
@jcarpent if you are reverting back to the original proposition, I would also remove 
b4571aa

**Pull request merged**
