### PR TITLE
Update to new hpp-fcl namespace wrapping

### PR DESCRIPTION
**Pull request by olivier-roussel**
Namespaces in hpp-fcl are now encapsulated inside hpp namespace (hpp-fcl commit 788afa0d )

### CODE REVIEW

**Comment by jcarpent** [comment]
Good to see you here.
I think this PR is worth to combine with `topic/fcl-release` branch. Can you rebase on it or see with @jmirabel?

**Comment by nim65s** [comment]
I think that there is no issue with the hpp-fcl namespace, and that #645 was enough, especially with the `namespace fcl = hpp::fcl;`in src/multibody/fcl.hpp.

**Comment by nim65s** [comment]
But yes, @olivier-roussel you should use the `topic/fcl-release` branch if you want to use hpp-fcl v1.0+

**Comment by olivier-roussel** [comment]
My bad, trying to catch your workflow. Thanks, I guess we can close the PR.

**Pull request closed without merging**
