### PR TITLE
Fix issue with Python 3.6

### PR DESCRIPTION
**Pull request by jcarpent**
@duburcqa Could you check this fix on your side?

### CODE REVIEW

**Comment by nim65s** [comment]
@duburcqa : could you confirm that robotpkg-py36-eigenpy 2.9.1 still present issues on your side ?

**Comment by duburcqa** [comment]
Yes I will.

**Comment by duburcqa** [comment]
> Could you check this fix on your side?

It was not working but it was before your last commit, so it was not checking the right Python version. Trying again now.

**Comment by duburcqa** [comment]
@jcarpent It works!

**Comment by duburcqa** [comment]
> @duburcqa : could you confirm if robotpkg-py36-eigenpy 2.9.1 still present issues on your side ?

Still crashing.

**Comment by duburcqa** [comment]
You patch is not relevant for all Python versions ? Why only apply it to Python 3.6.9 ?

**Comment by jcarpent** [comment]
No, as you can see, the CI is fine for the other Ubuntu versions.

**Comment by jcarpent** [comment]
In general, I'm trying to fix what should be fixed and not apply a patch if it is not necessary elsewhere.
PS: the issue really seems to be coming from Boost.Python + Python 3.6

**Comment by duburcqa** [comment]
Ok no problem I'm fine with it ! Thank you for the patch !

**Pull request merged**
