### PR TITLE
Add inverse dynamics examples

### PR DESCRIPTION
**Pull request by stephane-caron**
Follow up to the [2 DoF gravity compensation](https://www.youtube.com/watch?v=jCM1n39dDWk) tutorial, where it was mentioned that a simple ID example was missing. Thanks @jpieper!

### CODE REVIEW

**Comment by hrp2-14** [comment]
Hi ! This project doesn't usually accept pull requests on the main branch.
If this wasn't intentionnal, you can change the base branch of this PR to devel
(No need to close it for that). Best, a bot.

**Comment by jorisv** [comment]
Add a new entry in CHANGELOG.md

**Review by jcarpent — APPROVED** [review]

**Comment by stephane-caron** [comment]
> Add a new entry in CHANGELOG.md

There is no changelog here yet! (But I agree, if there were one, I would totally have forgotten :stuck_out_tongue_winking_eye:)

**Comment by jorisv** [comment]
> > Add a new entry in CHANGELOG.md
> 
> There is no changelog here yet! (But I agree, if there were one, I would totally have forgotten 😜)

My bad, I confused it with EigenPy

**Review by jorisv — APPROVED** [review]

**Pull request merged**
