### PR TITLE
badges: add PyPI

### PR DESCRIPTION
**Pull request by nim65s**

### CODE REVIEW

**Review by jcarpent — APPROVED** [review]

**Review by wxmerkt — COMMENTED** [review]
While we are updating badges, we can remove the Travis badge and add a GitHub Actions CI badge?

**Comment by jcarpent** [comment]
@nim65s Could you handle it?

**Comment by nim65s** [comment]
The issue with Github Action CI badges is that we don't have one badge, but one badge per workflow. And we have : 

1. linux.yml  
2. macos-linux-conda.yml 
3. ros-ci.yml  
4. windows-conda-clang.yml  
5. windows-conda-v142.yml

What should we do ?

ref. https://docs.github.com/en/actions/managing-workflow-runs/adding-a-workflow-status-badge

**Comment by jcarpent** [comment]
Maybe, we should put a table with CI on ROS, ubuntu (apt), mac (conda), windows (conda).

**Comment by wxmerkt** [comment]
Additional builds from the ROS buildfarm are:
- 20.04 / Noetic devel branch ("Ndev"): [Build Status](https://build.ros.org/job/Ndev__pinocchio__ubuntu_focal_amd64/)
- 18.04 / Melodic devel branch ("Mdev"): [Build Status](https://build.ros.org/job/Mdev__pinocchio__ubuntu_bionic_amd64/)
- 20.04 / Noetic binary (there are a few, this is amd64): [Build Status](https://build.ros.org/job/Nbin_uF64__pinocchio__ubuntu_focal_amd64__binary/)
- 18.04 / Melodic binary (there are a few, this is amd64): [Build Status](https://build.ros.org/job/Mbin_uB64__pinocchio__ubuntu_bionic_amd64__binary/)

**Comment by jcarpent** [comment]
@nim65s Any update on this PR?

**Review by jcarpent — APPROVED** [review]

**Comment by nim65s** [comment]
[RENDERED](https://github.com/nim65s/pinocchio/blob/devel/README.md). I am not convinced. If anyone has better graphic communication skills, don't hesitate :)

**Comment by nim65s** [comment]
Oops, didn't saw your commits while I was amending mine :/ I'm done pushing, you can change what you need.

**Comment by jcarpent** [comment]
you can stash the commits if you want, I have used the web interface which is a bit limited

**Pull request merged**
