### PR TITLE
Pinocchio 3

### PR DESCRIPTION
**Pull request by jorisv**
All Pinocchio 3 development.

Improvement are stored in CHANGELOG.md.

TODO:

- [x] Manage new dependencies
  - [x] Release Pycppad with a recent eigenpy version on Windows
  - [x] Release pycppad with cppad 2023 on Windows ? (since codegen is never used on Windows, it's useless)
- [x] Local convention by default
  - [x] ABA
     - Set in a details/impl namespace
     - only use aba
  - [x] CRBA
- [x] Remove abort
- [x] setup back old GeometryObject constructor that wasn't deprecated in pinocchio 2
- [x] Green CI
  - Linux Release
    - [x] test-cpp-cppad-joints
      - Fail caused by -fstack-protector-strong
      - valgrind trigger some errors
  - Linux Debug
    - [x] Disk space issue…
  - Macos Release
    - [x] test-cpp-constrained-dynamics
    - [x] test-cpp-cppad-joints
    - [x] test-cpp-casadi-explog
  - Macos Debug
    - [x] test-cpp-constrained-dynamics
    - [x] test-cpp-cppad-joints
    - [x] test-cpp-casadi-explog
    - [x] test-cpp-casadi-joints
    - [x] example-py-autodiff-rnea
    - [x] example-py-codegen-rnea
      - Add [CPPAD_DEBUG_AND_RELEASE flag](https://coin-or.github.io/CppAD/doc/preprocessor.htm#Documented%20Here.CPPAD_DEBUG_AND_RELEASE)
  - Ubuntu 20.04
    - [x] Fix expose-collision.cpp
    - [x] Fix casadi python binding crash
- [x] Test dependencies
  - [x] exemple-robot-data
  - [x] proxsuite-nlp
  - [x] aligator
  - [x] proxsuite
  - [x] crocoddyl
  - [x] tsid

### CODE REVIEW

**Comment by nim65s** [comment]
Congratulations 🎉 

I'll double check this asap

**Comment by jcarpent** [comment]
🥳 Nice achievements and team work powered by the [Willow team](https://www.di.ens.fr/willow/) [@INRIA](http://www.inria.fr) !!!

**Comment by proyan** [comment]
This deserves champagne at INRIA tonight 🎊 
Congrats!

**Comment by jcarpent** [comment]
> This deserves champagne at INRIA tonight 🎊 Congrats!

At Inria, some people (I won't name here) would prefer Côte-Rôtie ;)

**Comment by gabrielebndn** [comment]
Great news, congratulations :tada:

**Review by jcarpent — APPROVED** [review]

**Comment by ManifoldFR** [comment]
Congratulations everyone !!! 🥳 🥳 🥳

**Comment by gabrielebndn** [comment]
This is GREAT! Congrats for a huge work :slightly_smiling_face:

**Pull request merged**
