### PR TITLE
Specialize log for autodiff

### PR DESCRIPTION
**Pull request by proyan**
Currenty Work in progress

### CODE REVIEW

**Comment by proyan** [comment]
Go ahead. That is why I pushed the wip version.

**Comment by proyan** [comment]
For now, I have an integrated test in crocoddyl that uses log3 and log6. Both are good according to the test. I'm preparing the unittests for pinocchio.

Meanwhile, could you please have a look at the implementation, and see if you have any comments?

**Comment by proyan** [comment]
Currently, the template arguments `ADMatrix3Like, _Scalar` for log3Algo are redundant. We only need the argument `Scalar`. However, I don't see how to obtain something like `ADMatrix3Like` from the `Scalar` type.
Do you have an insight?

**Comment by jcarpent** [comment]
I will make a pass after your push the tests. It will be easier in this way to check the modif.

**Pull request merged**
