### PR TITLE
Add RVizVisualizer

### PR DESCRIPTION
**Pull request by EtienneAr**
Basic implementation to use RViz as visualizer.

### CODE REVIEW

**Review by jcarpent — CHANGES_REQUESTED** [review]
Very nice job @EtienneAr. 
Could you mention the default minimal command lines to install the rviz python bindings (e.g with conda) in the Readme?

**Comment by EtienneAr** [comment]
@jcarpent, I updated both README in 863d3fc760f70534aebc73e973ca77d588b6574f

**Review by jcarpent — APPROVED** [review]
Sounds good to me.
I will try on my computer ;)

**Review by cmastalli — COMMENTED** [review]
The marker Rviz plugin is not the ideal solution. Instead, you might look the whole-body state rviz plugin (look in loco-3d organisation).

This plugin can display robot meshes, contact forces, CoM position and velocity, COP, friction come, etc.

This plugin also can visualize trajectories. We are heavily using it in our robots.

**Comment by jcarpent** [comment]
> The marker Rviz plugin is not the ideal solution. Instead, you might look the whole-body state rviz plugin (look in loco-3d organisation).
> 
> This plugin can display robot meshes, contact forces, CoM position and velocity, COP, friction come, etc.
> 
> This plugin also can visualize trajectories. We are heavily using it in our robots.

Please make comments in the code directly @cmastalli with links to precise codes in the package you have mentioned. It will definitely help @EtienneAr to improve his PR.

**Comment by jcarpent** [comment]
@cmastalli The goal of this viewer is to be flexible, easy to use and mostly written in Python for easy and flexible extensions.

**Comment by cmastalli** [comment]
> @cmastalli The goal of this viewer is to be flexible, easy to use and mostly written in Python for easy and flexible extensions.

You can use the whole-body state plugin with Python code. Just need to write a publisher that contains the whole-body state msgs.

Check out the plugin here: https://github.com/loco-3d/whole_body_state_rviz_plugin

If this solution is in your interested, I could provide more details on the code

**Comment by cmastalli** [comment]
Btw, this plugin is based on Pinocchio ;)

**Comment by jcarpent** [comment]
The thing is that we may want to add additional features (buttons, players, loading FLC geometry on the flight, etc.) and have the flexibility to create a GUI for specific applications without having to write C++ codes, as offered by RVIZ+Qt.
Your interface seems to be too much specific and linked to locomotion mostly.

**Comment by jcarpent** [comment]
> Btw, this plugin is based on Pinocchio ;)

Pinocchio cannot rely on a lib ... which also depends on Pinocchio.

**Comment by cmastalli** [comment]
The plugin applies to any robot. It uses urdf loaded in the parameter server. Thus, you could load your FCL geometry (i.e., custom urdf). A code that use this plugin will depend on the whole-body state msg only (so not recursive dependency).

**Comment by jcarpent** [comment]
Working totally fine on my side. Thanks again @EtienneAr for this nice work.

**Pull request merged**
