### PR TITLE
Build library only if sources are detected.

### PR DESCRIPTION
**Pull request by aelkhour**

### CODE REVIEW

**Comment by jcarpent** [comment]
I do not think that it the proper way to handle such situation where the library is empty.
In this situation, you have to create a cmake variable which will be true as soon as the ${PROJECT_NAME}_SOURCES list is not empty.

Have you got some issues with an empty lib ?

**Comment by aelkhour** [comment]
Compilation fails with qcc when there are no sources, which is why I added the test.

I'll try to propose a cleaner way if it's ok for you.

**Comment by jcarpent** [comment]
Ok, I understand.

So, a cleaner solution may be to add a global variable which indicates if the compilation of the main library is needed or not (i.e. emptiness).

**Comment by aelkhour** [comment]
New proposal.

**Comment by jcarpent** [comment]
Ok. Just to avoid confusions, could you just change BUILD_LIBRARY into BUILD_MAIN_LIBRARY ?

**Comment by aelkhour** [comment]
Done.

**Comment by aelkhour** [comment]
This issue has been fixed in the devel branch. I use on a daily basis, so I would recommend using it, but you might want to double-check with @jcarpent.

**Comment by fvalenza** [comment]
As stated by @aelkhour , there was a hotfix in the devel branhc. If i remember it's commit c8ff00

**Pull request merged**
