### PR TITLE
Increase support of static-if, and autodiff

### PR DESCRIPTION
**Pull request by proyan**
This PR develops on the static-if implementation, and increases support of casadi and cppad scalar types.

### CODE REVIEW

**Comment by proyan** [comment]
When compiling pinocchio with casadi support `ON` in the current pinocchio release 2.4.1, I get the following error:

```
[  8%] Building CXX object unittest/CMakeFiles/test-cpp-value.dir/value.cpp.o
cd /local/rbudhira/devel/build/sot/pinocchio/_build-RELEASE/unittest && /usr/bin/c++   -DBOOST_MPL_LIMIT_LIST_SIZE=30 -DBOOST_MPL_LIMIT_VECTOR_SIZE=30 -DPINOCCHIO_CPPAD_REQUIRES_MATRIX_BASE_PLUGIN -DPINOCCHIO_WITH_CASADI_SUPPORT -DPINOCCHIO_WITH_CPPADCG_SUPPORT -DPINOCCHIO_WITH_CPPAD_SUPPORT -DPINOCCHIO_WITH_HPP_FCL -DPINOCCHIO_WITH_URDFDOM -I/local/rbudhira/devel/build/sot/pinocchio/_build-RELEASE -I/local/rbudhira/devel/build/sot/pinocchio/_build-RELEASE/include -I/home/rbudhira/devel/src/sot/pinocchio/include -I/home/rbudhira/devel/src/sot/pinocchio/unittest -isystem /usr/include/eigen3 -isystem /local/rbudhira/devel/install/sot/include -isystem /opt/ros/kinetic/include -isystem /usr/include/assimp  -pedantic -Wno-long-long -Wall -Wextra -Wcast-align -Wcast-qual -Wformat -Wwrite-strings -Wconversion  -O3 -DNDEBUG    -DBOOST_TEST_DYN_LINK -DBOOST_TEST_MODULE=valueTest '-DPINOCCHIO_MODEL_DIR="/home/rbudhira/devel/src/sot/pinocchio/models"' -DHPP_FCL_HAVE_OCTOMAP -DFCL_HAVE_OCTOMAP -DOCTOMAP_MAJOR_VERSION=1 -DOCTOMAP_MINOR_VERSION=8 -DOCTOMAP_PATCH_VERSION=1 -o CMakeFiles/test-cpp-value.dir/value.cpp.o -c /home/rbudhira/devel/src/sot/pinocchio/unittest/value.cpp
In file included from /local/rbudhira/devel/build/sot/pinocchio/_build-RELEASE/include/pinocchio/spatial/se3.hpp:44:0,
                 from /local/rbudhira/devel/build/sot/pinocchio/_build-RELEASE/include/pinocchio/multibody/model.hpp:10,
                 from /local/rbudhira/devel/build/sot/pinocchio/_build-RELEASE/include/pinocchio/algorithm/rnea.hpp:8,
                 from /home/rbudhira/devel/src/sot/pinocchio/unittest/casadi-algo-derivatives.cpp:7:
/local/rbudhira/devel/build/sot/pinocchio/_build-RELEASE/include/pinocchio/spatial/se3-tpl.hpp: In instantiation of ‘pinocchio::SE3Tpl<NewScalar, Options> pinocchio::SE3Tpl<Scalar, Options>::cast() const [with NewScalar = casadi::Matrix<casadi::SXElem>; _Scalar = double; int _Options = 0]’:
/local/rbudhira/devel/build/sot/pinocchio/_build-RELEASE/include/pinocchio/multibody/model.hpp:235:32:   required from ‘pinocchio::ModelTpl<NewScalar, Options, JointCollectionTpl> pinocchio::ModelTpl<Scalar, Options, JointCollectionTpl>::cast() const [with NewScalar = casadi::Matrix<casadi::SXElem>; _Scalar = double; int _Options = 0; JointCollectionTpl = pinocchio::JointCollectionDefaultTpl]’
/home/rbudhira/devel/src/sot/pinocchio/unittest/casadi-algo-derivatives.cpp:47:43:   required from here
/local/rbudhira/devel/build/sot/pinocchio/_build-RELEASE/include/pinocchio/spatial/se3-tpl.hpp:292:7: error: could not convert ‘casadi::operator>(const casadi::Matrix<casadi::SXElem>&, const casadi::Matrix<casadi::SXElem>&)(casadi::Matrix<casadi::SXElem>(Eigen::NumTraits<casadi::Matrix<T> >::epsilon<casadi::SXElem>()))’ from ‘casadi::Matrix<casadi::SXElem>’ to ‘bool’
       if(pinocchio::cast<NewScalar>(Eigen::NumTraits<Scalar>::epsilon()) > Eigen::NumTraits<NewScalar>::epsilon())

```

https://github.com/stack-of-tasks/pinocchio/blob/master/src/spatial/se3-tpl.hpp#L292 is not well supported by autodiff types, it causes a compilation error with casadi, and I think it might cause a run-time numerical error with CppAD.

I'm not sure what would be the best way to deal with this, input would be welcome @jcarpent

**Comment by proyan** [comment]
@jcarpent I'm fixing something in math/quaternion.hpp. Please hold a bit before merging this PR. However, I would appreciate if you could help with https://github.com/stack-of-tasks/pinocchio/blob/master/src/spatial/se3-tpl.hpp#L292 as well.

On a similar topic, I see that there is a parallel PR that plans to use Eigen module for rpy operations. Are you dealing with math/quaternion in this PR as well?

**Comment by jcarpent** [comment]
The issue for the cast is solved thanks to my commits.
You can proceed for the quaternion side.

For the RPY, I will just work on making the code more robust in terms of numerics.

**Comment by proyan** [comment]
Cool. I have some comments about your commits. I'm making them now.

Thanks a lot for the support!

**Comment by jcarpent** [comment]
@proyan Are you now done?

**Comment by proyan** [comment]
Not yet. I'm confirming a few tests in crocoddyl. Please leave this open for a bit.

**Comment by proyan** [comment]
Hi @jcarpent 
If you have modifications to make, please go ahead. I don't make the changes that I suggested in the comments, since they deal with your modifications. I let you handle it.

On a different note, there is two different definitions of comparison-operators that we have in pinocchio now, one inside `utils/static-if.hpp`, and another inside `math/comparison-operators.hpp`. I suggest to keep just one if possible, two is too confusing. The struct `apply_op_if` is currently only being used inside `math/quaternion.hpp`. Should we remove it somehow?

**Comment by jcarpent** [comment]
> For now, I have a memory violation in `math/quaternion.hpp`, and I suspect it is coming from here.
In debug mode?

**Comment by jcarpent** [comment]
> If you have modifications to make, please go ahead. I don't make the changes that I suggested in the comments, since they deal with your modifications. I let you handle it.

I don't get the change your are suggesting. Can you be more precise?

**Comment by jcarpent** [comment]
> On a different note, there is two different definitions of comparison-operators that we have in pinocchio now, one inside `utils/static-if.hpp`, and another inside `math/comparison-operators.hpp`. I suggest to keep just one if possible, two is too confusing. The struct `apply_op_if` is currently only being used inside `math/quaternion.hpp`. Should we remove it somehow?

For the time being, we can keep it. I do not see other way to get this feature because of the bool output.

**Comment by jcarpent** [comment]
@proyan Before merging, I would like to change the signature of the if_then_else helper to have something like:
`lhs,OP,rhs,...`
instead of the current one:
`OP,lhs,rhs`

**Comment by proyan** [comment]
I like the signature right now. It makes it easier to separate the value arguments from the comparison operators. I think it would be confusing if you put it in the middle, `op` might be confused with a local variable. But it is not a strong preference. I'm okay either way.

**Comment by proyan** [comment]
The if comparison at https://github.com/proyan/pinocchio/blob/devel/src/multibody/liegroup/vector-space.hpp#L146 is not suitable for autodiff types. For now I've let it be.

**Comment by proyan** [comment]
I don't think that the buildfarm liked the addition of casdi. Currently the `make` fails with following error:
```make
tmp/ccA0Y4JL.s: Assembler messages:
/tmp/ccA0Y4JL.s: Fatal error: can't close CMakeFiles/test-cpp-joint-revolute.dir/joint-revolute.cpp.o: No space left on device
##[error]No space left on device
```

**Comment by jcarpent** [comment]
> I don't think that the buildfarm liked the addition of casdi. Currently the `make` fails with following error:
> 
> ```makefile
> tmp/ccA0Y4JL.s: Assembler messages:
> /tmp/ccA0Y4JL.s: Fatal error: can't close CMakeFiles/test-cpp-joint-revolute.dir/joint-revolute.cpp.o: No space left on device
> ##[error]No space left on device
> ```

This is not due to Casadi at all, but to internal issue inside Gihub Action.

**Comment by proyan** [comment]
This PR is ready to be merged.

**Pull request merged**
