### PR TITLE
[C++] GeometryObject parent is a frame of type BODY

### PR DESCRIPTION
**Pull request by jmirabel**
Refers to https://github.com/humanoid-path-planner/hpp-pinocchio/issues/34

### CODE REVIEW

**Comment by jmirabel** [comment]
I do not know how to update the Python bindings myself. Can someone give me a hint ?

I can as well remove the reference to Model in GeometryModel (and pass it by arguments when needed).

**Comment by jcarpent** [comment]
I think we need to really think twice before adding a const ref on the model inside GeomModel. But I think it is mandatory for your case.

So to sum up the situation, the idea is we have two trees inside the mode:
- a minimal one which contains only joints with at least one DoF and the tree can be retrieve through `model.parents` vector
- a large one, which contains all the frames that a robot can contain: SENSORS, BODIES, JOINTS, FIXED JOINTS, OPERATIONAL_FRAMES, etc. The minimal one can be retrieve from the large one. This large tree is accessible trough `model.frames`vector.

The idea is then to allows frames to index for example body frames as parent and not only joints as it is currently done.

Can we discuss that tomorrow with @florent-lamiraux?

**Comment by jcarpent** [comment]
I can then explain you how to update the Python interface. It is not difficult, but maybe hard to explain through the Github interface.

**Comment by jmirabel** [comment]
> I think we need to really think twice before adding a const ref on the model inside GeomModel. But I think it is mandatory for your case.

I can just add an argument to every function requiring the Model and not add a const ref to the Model, cannot I ?

**Comment by jmirabel** [comment]
I have updated the code to remove the const reference to Model in GeometryModel.

Following #299, I close this pull-request and push to branch hpp-devel.

**Comment by jmirabel** [comment]
Note that some bugs in the URDF parser have been fixed.

**Pull request closed without merging**
