### PR TITLE
modernize python code base, part 2

### PR DESCRIPTION
**Pull request by nim65s**
Hi,

This follow #2367 by enabling additional opt-in features of ruff, and implementing those either manually or through auto-fix.

Commit history was rewritten to ease review, but things can be squashed once agreed.

### CODE REVIEW

**Comment by hrp2-14** [comment]
Hi ! This project doesn't usually accept pull requests on the main branch.
If this wasn't intentionnal, you can change the base branch of this PR to devel
(No need to close it for that). Best, a bot.

**Comment by ManifoldFR** [comment]
Great work again @nim65s :)

**Review by jcarpent — CHANGES_REQUESTED** [review]
Thanks @nim65s for the cleanage of the code.
Could you squeeze everything into a single commit?

**Comment by nim65s** [comment]
done

**Comment by nim65s** [comment]
macos CI is consistently failing with:
```cmake
CMake Error at CMakeLists.txt:324 (message):
  Your version of Eigen is too low.  Should be at least 3.4.90.  Current
  version is 3.4.0.
```
windows CI is failing with
```
C:\Miniconda\envs\pinocchio\Library\include\cppad/cg/cg.hpp(217): error C2143: syntax error: missing ';' before '<'
C:\Miniconda\envs\pinocchio\Library\include\cppad/cg/cg.hpp(217): error C2433: 'CppAD::cg::NearEqual': 'friend' not permitted on data declarations
C:\Miniconda\envs\pinocchio\Library\include\cppad/cg/cg.hpp(217): error C2365: 'CppAD::cg::NearEqual': redefinition; previous definition was 'function'
```


In both cases, this is not related to this PR.

**Comment by jcarpent** [comment]
> macos CI is consistently failing with:
> 
> ```cmake
> CMake Error at CMakeLists.txt:324 (message):
>   Your version of Eigen is too low.  Should be at least 3.4.90.  Current
>   version is 3.4.0.
> ```

For this issue, I've removed the support Apple Accelerate for `build_all`

**Pull request merged**
