### PR TITLE
[C++] Added JointAccessor + its unittests.

### PR DESCRIPTION
**Pull request by fvalenza**
Major : Added JointModelAccessor and JointDataAccessor that are an abstraction (more precisely a mapping) on Variant types and that expose all the API of JointBase through the use of visitors. Theses visitors have been moved to another file to facilitate the documentation.
Added related unittest

### CODE REVIEW

**Comment by jcarpent** [comment]
According to me, the unit test can be largely improved by using for_each on the joint model and data variants.

**Comment by jcarpent** [comment]
Related to #131.

**Comment by jcarpent** [comment]
I was maybe too fast. 
@fvalenza Do you try to make JointVariant inheriting both from boost::variant and from JointModel ?

**Comment by fvalenza** [comment]
Not yet. It is one of the future things to test. As it is now it maps a
joint as stated previously
Le 23 mai 2016 21:27, "Justin Carpentier" <notifications@github.com> a
écrit :

**Pull request merged**
