### PR TITLE
Deactivate unfixed warnings

### PR DESCRIPTION
**Pull request by wxmerkt**
This PR deactivates two kinds of warnings as they are unlikely to be fixed in code and may hide important warnings that are worth fixing:

- **Conversion:** In general, I am hesitant in deactivating this warning due to `double` to `int` conversion bugs. However, we get a ton of these warnings due to `BOOST_PYTHON_FUNCTION_OVERLOADS`.
- **Multi-line comment:** There are two sources (a) commented out macros that appear as multi-line comments and (b) Latex code.

This reduces our compiler warnings from at present 104 to 3.

The remaining warnings after this PR are:
```
In file included from ~/git/pinocchio/build/include/pinocchio/math/quaternion.hpp:11:0,
                 from ~/git/pinocchio/build/include/pinocchio/spatial/se3-tpl.hpp:12,
                 from ~/git/pinocchio/build/include/pinocchio/spatial/se3.hpp:44,
                 from ~/git/pinocchio/build/include/pinocchio/multibody/model.hpp:10,
                 from ~/git/pinocchio/build/include/pinocchio/algorithm/joint-configuration.hpp:8,
                 from ~/git/pinocchio/bindings/python/algorithm/expose-joints.cpp:6:
~/git/pinocchio/build/include/pinocchio/utils/static-if.hpp: In static member function ‘static pinocchio::internal::if_then_else_impl<condition_type, condition_type, ThenType, ElseType>::ReturnType pinocchio::internal::if_then_else_impl<condition_type, condition_type, ThenType, ElseType>::run(pinocchio::internal::ComparisonOperators, const condition_type&, const condition_type&, const ThenType&, const ElseType&) [with condition_type = double; ThenType = double; ElseType = double]’:
~/git/pinocchio/build/include/pinocchio/utils/static-if.hpp:71:7: warning: control reaches end of non-void function [-Wreturn-type]
       }
       ^
In file included from ~/git/pinocchio/build/include/pinocchio/spatial/explog.hpp:10:0,
                 from ~/git/pinocchio/build/include/pinocchio/bindings/python/spatial/explog.hpp:9,
                 from ~/git/pinocchio/bindings/python/spatial/expose-explog.cpp:6:
~/git/pinocchio/build/include/pinocchio/utils/static-if.hpp: In static member function ‘static pinocchio::internal::if_then_else_impl<condition_type, condition_type, ThenType, ElseType>::ReturnType pinocchio::internal::if_then_else_impl<condition_type, condition_type, ThenType, ElseType>::run(pinocchio::internal::ComparisonOperators, const condition_type&, const condition_type&, const ThenType&, const ElseType&) [with condition_type = double; ThenType = double; ElseType = double]’:
~/git/pinocchio/build/include/pinocchio/utils/static-if.hpp:71:7: warning: control reaches end of non-void function [-Wreturn-type]
       }
       ^
In file included from ~/git/pinocchio/build/include/pinocchio/math/quaternion.hpp:11:0,
                 from ~/git/pinocchio/build/include/pinocchio/spatial/se3-tpl.hpp:12,
                 from ~/git/pinocchio/build/include/pinocchio/spatial/se3.hpp:44,
                 from ~/git/pinocchio/build/include/pinocchio/bindings/python/spatial/se3.hpp:12,
                 from ~/git/pinocchio/bindings/python/spatial/expose-SE3.cpp:6:
~/git/pinocchio/build/include/pinocchio/utils/static-if.hpp: In static member function ‘static pinocchio::internal::if_then_else_impl<condition_type, condition_type, ThenType, ElseType>::ReturnType pinocchio::internal::if_then_else_impl<condition_type, condition_type, ThenType, ElseType>::run(pinocchio::internal::ComparisonOperators, const condition_type&, const condition_type&, const ThenType&, const ElseType&) [with condition_type = double; ThenType = double; ElseType = double]’:
~/git/pinocchio/build/include/pinocchio/utils/static-if.hpp:71:7: warning: control reaches end of non-void function [-Wreturn-type]
       }
       ^
```

### CODE REVIEW

**Comment by jcarpent** [comment]
Issue from GitHub. This PR has been merged but has not been closed.

**Comment by gabrielebndn** [comment]
I had noticed the conversion warnings and I wanted to get rid of them. However, I had trouble with that,  naive approaches did not seem to work

**Comment by wxmerkt** [comment]
> I had noticed the conversion warnings from BOOST_PYTHON_FUNCTION_OVERLOADS and I wanted to get rid of them. However, I had trouble with that, naive approaches did not seem to work

I did spent a significant amount of time trying to get rid off them "properly" but none of the usual suspects (casting, appending type specifiers, etc.) worked :-(. If you have an idea for a better solution, let's fix them proper and re-activate the warning.

**Comment by gabrielebndn** [comment]
> > I had noticed the conversion warnings from BOOST_PYTHON_FUNCTION_OVERLOADS and I wanted to get rid of them. However, I had trouble with that, naive approaches did not seem to work
> 
> I did spent a significant amount of time trying to get rid off them "properly" but none of the usual suspects (casting, appending type specifiers, etc.) worked :-(. If you have an idea for a better solution, let's fix them proper and re-activate the warning.

Same here. Tried but failed. Weird. I fear this warning may come from inside boost, and there may be nothing we can do about it. And I haven't found anything on the internet about it either. The only "better" solution I can think of is to locally ignore the warning putting `#pragma` around each instance of `BOOST_PYTHON_FUNCTION_OVERLOADS`, but I'm not even sure it can actually be considered "better".

**Comment by aelkhour** [comment]
> > > I had noticed the conversion warnings from BOOST_PYTHON_FUNCTION_OVERLOADS and I wanted to get rid of them. However, I had trouble with that, naive approaches did not seem to work
> > 
> > 
> > I did spent a significant amount of time trying to get rid off them "properly" but none of the usual suspects (casting, appending type specifiers, etc.) worked :-(. If you have an idea for a better solution, let's fix them proper and re-activate the warning.
> 
> Same here. Tried but failed. Weird. I fear this warning may come from inside boost, and there may be nothing we can do about it. And I haven't found anything on the internet about it either. The only "better" solution I can think of is to locally ignore the warning putting `#pragma` around each instance of `BOOST_PYTHON_FUNCTION_OVERLOADS`, but I'm not even sure it can actually be considered "better".

I spent some time investigating this, and as I recall there is no issue on the caller side, it's just the boost macro implementation that seems to be problematic.

I think that @gabrielebndn's proposal of using `#pragma` is the way to go in this specific case, the same way one would use `-isystem` to silence system header warnings.

**Comment by gabrielebndn** [comment]
@wxmerkt, I now see that your `-Wno-conversion` is limited to the Python wrappings. In this case it's good, as Python bindings contain hardly any function code, and I think there is no point wasting more time on this.

**Pull request closed without merging**
