### PR TITLE
Add example for CRBA codegen

### PR DESCRIPTION
**Pull request by jcarpent**
@vpadois

This feature is for you and related to #1047

### CODE REVIEW

**Comment by jcarpent** [comment]
@vpadois
To make the example working, you have to install CppAD (release 20200000.2 from https://github.com/coin-or/CppAD) and also CppADCodeGen (release v2.3.0 from https://github.com/joaoleal/CppADCodeGen)

**Comment by vpadois** [comment]
@jcarpent Thanks for this information. I have to put this on hold for a few days but I will come back to you ASAP.

Thanks again.

**Comment by LucasJoseph** [comment]
Hello,

I'm looking at this with @vpadois, and we were wondering if there is a way to access the symbolic model generated by cppadcg as shown [here](https://github.com/joaoleal/CppADCodeGen/wiki#c-language) ? I cannot find a way to make it work with the your example.

**Comment by jcarpent** [comment]
You should at the code in the class helper and just change the code generator, from C to latex for instance.

**Pull request merged**
