### PR TITLE
[bindings] Implement bindings, solve name inconsistencies, fix #529

### LINKED ISSUE #529: [bindings] Function naming inconsistencies between Python and C++
The following methods have a Python name which is different from the C++ name:
- impulseDynamics (impactDynamics in C++)
- nle (nonLinearEffects in C++)

### PR DESCRIPTION
**Pull request by gabrielebndn**
I moved my changes in #531 from my devel branch to a dedicated topic branch.
This pull request replaces #531, see there for earlier discussion.
Compared to #531, I rolled back the correction in the python test folder, as that will be the object of a future pull request, either from me or from Guilhem

### CODE REVIEW

**Comment by jcarpent** [comment]
Do not open new PR for that, just remove unnecessary part of the commits.

**Comment by gabrielebndn** [comment]
It is not about the unnecessary commit. Right now, the changes are on my devel branch, but I want to move them on a dedicated topic branch in order to have my devel branch on par with Pinocchio. Apparently, github does not allow to change the base branch of a pull request, so I have to open a new pull request for that. I apologize for that, I should have put it on a topic branch from the start, next time I will remember that. Really, the two requests are identical (except for that small difference), it's just a matter of organization.

**Comment by jcarpent** [comment]
You should change next time, not during a review process. This is a bit annoying for the people who do the review of the code and the management of the project.

**Comment by gabrielebndn** [comment]
Alright, I apologize, I'll stay with my devel branch as it is. I will remove the unnecessary commit there

**Pull request closed without merging**
