### PR TITLE
Fix issue related HPP-FCL support

### PR DESCRIPTION
**Pull request by jcarpent**
This is related to #757.

### CODE REVIEW

**Comment by jviereck** [comment]
Thanks for providing this PR @jcarpent.

Testing this on macOS:

1. The source compiles when using the default options. When using the default options, the mesh_scale size is still 1 though (see #757)
2. When turn on `BUILD_WITH_COLLISION_SUPPORT` in the CMakeList.txt file, I get the error below



```
[ 53%] Building CXX object unittest/CMakeFiles/model.dir/model.cpp.o
cd /Users/jviereck/dev/tools/pinocchio/build26/unittest && /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++  -DPINOCCHIO_URDFDOM_TYPEDEF_SHARED_PTR -DPINOCCHIO_URDFDOM_USE_STD_SHARED_PTR -DPINOCCHIO_WITH_HPP_FCL -DPINOCCHIO_WITH_URDFDOM -I/Users/jviereck/dev/tools/pinocchio/build26 -I/Users/jviereck/dev/tools/pinocchio/build26/include -I/Users/jviereck/dev/tools/pinocchio/include -I/Users/jviereck/dev/tools/pinocchio/unittest -isystem /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/python2.7 -isystem /usr/local/include -isystem /usr/local/Cellar/eigen/3.3.7/include/eigen3 -isystem /usr/local/Cellar/hpp-fcl/1.0.1/include -isystem /usr/local/Cellar/octomap/1.9.0/include -isystem /usr/local/Cellar/assimp/4.1.0/include -isystem /usr/local/Cellar/urdfdom/1.0.3/include -isystem /usr/local/Cellar/urdfdom_headers/1.0.3/include -isystem /usr/local/Cellar/console_bridge/0.4.3/include  -pedantic -Wno-long-long -Wall -Wextra -Wcast-align -Wcast-qual -Wformat -Wwrite-strings -Wconversion  -O3 -DNDEBUG -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk    -DBOOST_TEST_DYN_LINK -DBOOST_TEST_MODULE=modelTest -DFCL_USE_ASSIMP_UNIFIED_HEADER_NAMES -DHPP_FCL_USE_ASSIMP_UNIFIED_HEADER_NAMES -DHPP_FCL_HAVE_OCTOMAP -DFCL_HAVE_OCTOMAP -DOCTOMAP_MAJOR_VERSION=1 -DOCTOMAP_MINOR_VERSION=9 -DOCTOMAP_PATCH_VERSION=0 -o CMakeFiles/model.dir/model.cpp.o -c /Users/jviereck/dev/tools/pinocchio/unittest/model.cpp
/Users/jviereck/dev/tools/pinocchio/unittest/model.cpp:69:5: error: use of undeclared identifier
      'BOOST_MESSAGE'
    BOOST_MESSAGE(manipulator);
    ^
/Users/jviereck/dev/tools/pinocchio/unittest/model.cpp:80:5: error: use of undeclared identifier
      'BOOST_MESSAGE'
    BOOST_MESSAGE(humanoid);
    ^
/Users/jviereck/dev/tools/pinocchio/unittest/model.cpp:85:31: warning: implicit conversion changes
      signedness: 'int' to 'pinocchio::FrameIndex' (aka 'unsigned long') [-Wsign-conversion]
    FrameIndex fid = humanoid.addFrame (Frame ("humanoid/add_manipulator",
               ~~~   ~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/jviereck/dev/tools/pinocchio/unittest/model.cpp:93:5: error: use of undeclared identifier
      'BOOST_MESSAGE'
    BOOST_MESSAGE(model);
    ^
/Users/jviereck/dev/tools/pinocchio/unittest/model.cpp:102:39: error: invalid operands to binary expression
      ('const char *' and 'pinocchio::JointIndex' (aka 'unsigned long'))
      BOOST_MESSAGE("Checking joint " << jid << " " << model.names[jid]);
                    ~~~~~~~~~~~~~~~~~ ^  ~~~
/Users/jviereck/dev/tools/pinocchio/unittest/model.cpp:107:37: error: invalid operands to binary expression
      ('const char *' and 'pinocchio::JointIndex' (aka 'unsigned long'))
    BOOST_MESSAGE("Checking joint " << chest2 << " " << model.names[chest2]);
                  ~~~~~~~~~~~~~~~~~ ^  ~~~~~~
/Users/jviereck/dev/tools/pinocchio/unittest/model.cpp:114:39: error: invalid operands to binary expression
      ('const char *' and 'unsigned long')
      BOOST_MESSAGE("Checking joint " << chest2+jid << " " << model.names[chest2+jid]);
                    ~~~~~~~~~~~~~~~~~ ^  ~~~~~~~~~~
/Users/jviereck/dev/tools/pinocchio/unittest/model.cpp:123:39: error: invalid operands to binary expression
      ('const char *' and 'unsigned long')
      BOOST_MESSAGE("Checking joint " << jid+manipulator.joints.size()-1 << " " << model.names[jid+m...
                    ~~~~~~~~~~~~~~~~~ ^  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by jcarpent** [comment]
@jviereck Thanks for this fast feedback. I will look at it this morning.

**Comment by jcarpent** [comment]
@jviereck I have fixed the two issues you mentioned. Can you confirm that everything works well with your setup?

**Comment by jviereck** [comment]
Thanks for providing the fixes @jcarpent.

This patch fixes #757. I can confirm that

1) the PR code compiles with and without the option BUILD_WITH_COLLISION_SUPPORT enabled
2) the urdf mesh scaling shows up correct in gepetto-gui when compiled with and without BUILD_WITH_COLLISION_SUPPORT enabled

**Pull request merged**
