### PR TITLE
Fix bug when compiling with C++11

### PR DESCRIPTION
**Pull request by jcarpent**
Thanks to @aelkazdadi for raising the issue.

### CODE REVIEW

**Comment by nim65s** [comment]
I was going to fill a bug for this, as this was preventing me from updating robotpkg's binary releases.
@proyan also got an issue with that.

Thanks for the fix !

**Comment by jcarpent** [comment]
@nim65s This means that you're still compiling using C++11 by default on robotpkg?

**Comment by nim65s** [comment]
Yes, I still don't have a solution to do otherwise.

**Comment by jcarpent** [comment]
One solution is to not have the flag for all the OS first, I would say.

**Pull request merged**
