### PR TITLE
[Python] fix ViewerConfigurationToXYZQUAT

### PR DESCRIPTION
**Pull request by nim65s**
Not sure if this PR is really useful, but it looks like we had some broken code…

### CODE REVIEW

**Comment by fvalenza** [comment]
It is, it is. In addition, it could be nice to change the notation a b c d into something more explicit (like q_x, q_y, q_z, q_w may be. What do you think @jcarpent ?)

**Comment by jcarpent** [comment]
Good. It is good to keep the convention x,y,z,w to denote the quaternion components.

**Comment by jcarpent** [comment]
Just before merging, can you change a,b,c,d into x,y,z,w for labelling of quaternion coefficients ?

**Comment by nim65s** [comment]
Done :)

**Comment by jcarpent** [comment]
:+1:

**Pull request merged**
