### PR TITLE
Implement explog functions using Eigen.

### PR DESCRIPTION
**Pull request by aelkhour**
PR status: Ready to merge

- [x] exp3
- [x] log3
- [x] exp6
- [x] log6
- [x] explog python bindings
- [x] unit tests

### CODE REVIEW

**Comment by jcarpent** [comment]
2 spaces, but there are some incoherent indentations along the code.

**Comment by jcarpent** [comment]
A just a small remark, I think your code could become more efficient by directly computing the exp3 manually, mainly in expo function. Indeed, there is a lot of redundant computations done either in exp3 through Eigen AngleAxis and in the computation of what you call V

**Comment by aelkhour** [comment]
This PR does not include any unittests. It would be a good idea to add some, for both C++ and python.
How do you suggest we do that?

**Comment by jcarpent** [comment]
There is unittest directory in the project where you can easily add some new tests.

**Pull request merged**
