### PR TITLE
pinocchio/visualize: Add support for cone shape in meshcat dispaly

### PR DESCRIPTION
**Pull request by whtqh**
Add support for cone shape in Meshcat dispaly, which is discussed in #1768 .

### CODE REVIEW

**Comment by hrp2-14** [comment]
Hi ! This project doesn't usually accept pull requests on the main branch.
If this wasn't intentionnal, you can change the base branch of this PR to devel
(No need to close it for that). Best, a bot.

**Comment by jcarpent** [comment]
@whtqh I've just made a suggestion. Could you confirm that it works on your side?

**Comment by jcarpent** [comment]
@whtqh Here is a similar issue to yours https://github.com/JuliaRobotics/RigidBodyDynamics.jl/issues/589#issuecomment-943176446
Might be worth to add it within Pinocchio ;)
Thanks again for your nice contribution.

**Comment by whtqh** [comment]
> python/meshcat: use Cone primitives directly

It's a pity for meshcat that it does not have a cone primitive(See [Code](https://github.com/stack-of-tasks/pinocchio/blob/2a4953eca3886d7cfcc3037c6944fe2b892d70fb/bindings/python/pinocchio/visualize/meshcat_visualizer.py#L235) ):

```
/usr/local/lib/python3/dist-packages/pinocchio/visualize/meshcat_visualizer.py:341: UserWarning: Error while loading geometry object: obj4
Error message:
module 'meshcat.geometry' has no attribute 'Cone'
  self.loadViewerGeometryObject(visual,pin.GeometryType.VISUAL,color)
```

**Comment by whtqh** [comment]
> @whtqh Here is a similar issue to yours [JuliaRobotics/RigidBodyDynamics.jl#589 (comment)](https://github.com/JuliaRobotics/RigidBodyDynamics.jl/issues/589#issuecomment-943176446) Might be worth to add it within Pinocchio ;) Thanks again for your nice contribution.

I implemented an arrow geom model scripts as the same way of [Meshcat.jl](https://github.com/rdeits/MeshCat.jl/blob/e8cd09a2fc02fec46cb88b5c9347dac5b3d44719/src/arrow_visualizer.jl)
image

```
    def createArrowModel(start_point, end_point, color, name="arrow",
            shaft_diameter = 0.015, head_diameter = 0.02, head_length = 0.05):
        """Create Meshcat geom model contain geom_objs."""
        # http://wiki.ros.org/rviz/DisplayTypes/Marker
        start_p = start_point
        end_p = end_point
        # Calculates Rotation Matrix:
        print(start_p)
        print(end_p)
        geom_model = pin.GeometryModel()
        
        p_arrow = end_p - start_p
        p_cross_w_x = np.cross(p_arrow, np.array([1,0,0]))
        p_cross_w_y = np.cross(p_arrow, np.array([0,1,0]))
        p_cross_w_z = np.cross(p_arrow, np.array([0,0,1]))
        align_check = np.array([np.linalg.norm(p_cross_w_x) == 0, 
                    np.linalg.norm(p_cross_w_y) == 0,
                    np.linalg.norm(p_cross_w_z) == 0])
        cross_res = np.array([p_cross_w_x, p_cross_w_y, p_cross_w_z])
        if(np.sum(align_check!=0) > 1):
            print("length of array equals to zero.")
            placement = pin.SE3(np.eye(3), start_point)
            geom_obj = pin.GeometryObject(name + ": head", 0, 0, hppfcl.Cone(0.0, 0.0), placement)
            geom_model.addGeometryObject(geom_obj)
            return geom_model

        rot_mat_z = p_arrow
        rot_mat_y = np.array([0,0,0])
        rot_mat_x = np.array([0,0,0])

        i=0
        while i < len(align_check):
            if align_check[i] == False:
                rot_mat_x = np.cross(rot_mat_z, cross_res[i])
                break
            i += 1
        rot_mat_y = np.cross(rot_mat_z, rot_mat_x)
        rot_mat = np.eye(3)
        rot_mat[:,0] = rot_mat_x / np.linalg.norm(rot_mat_x)
        rot_mat[:,1] = rot_mat_y / np.linalg.norm(rot_mat_y)
        rot_mat[:,2] = rot_mat_z / np.linalg.norm(rot_mat_z)

        arrow_length = np.linalg.norm(end_p - start_p)
        shaft_length = 0
        if arrow_length < head_length:
            head_length = arrow_length
        else:
            shaft_length = arrow_length - head_length

        shaft_center_p = start_p + np.dot(rot_mat, np.array([0, 0, shaft_length / 2]))
        head_center_p = start_p + np.dot(rot_mat , np.array([0, 0, shaft_length + head_length / 2]))
        
        placement = pin.SE3(rot_mat, shaft_center_p)
        geom_obj = pin.GeometryObject(name + ": shaft", 0, 0, hppfcl.Cylinder(shaft_diameter / 2, shaft_length), placement)
        geom_obj.meshColor = color
        geom_model.addGeometryObject(geom_obj)

        placement = pin.SE3(rot_mat, head_center_p)
        geom_obj = pin.GeometryObject(name + ": head", 0, 0, hppfcl.Cone(head_diameter / 2, head_length), placement)
        geom_obj.meshColor = color
        geom_model.addGeometryObject(geom_obj)
        return geom_model
```

However, I temporarily put these lines in meshcat_visualizer.py, but there seems to be a better place.
And the geom_model should be reconfigurable, which is not supported in my code now.

**Comment by jcarpent** [comment]
The best way is not to add elements to the geom_model, but rather to add a helper to the Meshcat Viewer class in Pinocchio to add an arrow.

**Comment by whtqh** [comment]
> The best way is not to add elements to the geom_model, but rather to add a helper to the Meshcat Viewer class in Pinocchio to add an arrow.

https://github.com/tasts-robots/pink/blob/master/examples/meshcat_shapes.py
There exists a method to attach a new shape to the Meshcat viewer by passing a viewer handle, is it a proper way of a Meshcat helper?

**Comment by jcarpent** [comment]
> 

Yes, it seems to be a good idea to use this programing paradigm.

**Comment by jcarpent** [comment]
Thank you very much @whtqh for this nice contribution.

**Review by jcarpent — APPROVED** [review]

**Pull request merged**
