### PR TITLE
Improve packaging

### PR DESCRIPTION
**Pull request by jcarpent**
It follows #305 and the code proposition of https://github.com/olivier-stasse/pinocchio/tree/devel.

- The PYTHON_PASER can be build only if the PYTHON_INTERFACE is built
- EigenPy is no more added in the .pc file

### CODE REVIEW

**Comment by olivier-stasse** [comment]
Thanks this is in the good direction.
But keeping python.cpp in parser keeps links with python.
Then it creates python link error when linking with libpinocchio.
I do not see any alternative to put the file python.cpp in the libpinocchio_pywrap.

**Comment by jcarpent** [comment]
I agree with @olivier-stasse. I will follow your proposition to move the python parser to the python lib. In this way, people who needs the python wrapper would need to link against pinocchiopy

**Comment by jcarpent** [comment]
@olivier-stasse I propose to merge first this PR. I will open soon a new one concerning the shift of the Python parser to the Python lib.

**Comment by olivier-stasse** [comment]
@jcarpent : I may have a solution for python_parser.cpp which does not imply to modify the code.
The key is to not bind python_parser to eigenpy, pinocchio and pinocchio_pywrap but simply to libboost-python and python. 
A small customization of python_parser cmake instructions is needed.
You can use the 4 lines of file 
unittest/CMakeLists.txt
in commit d264bf6d6d7e22339753dd09567dee270d0eafba
Of course this implies also to bind the python parser with libpinocchio_pywrap
This would be a great addition to your current PR.

**Comment by jcarpent** [comment]
Thanks @olivier-stasse for your remarks. I'll take some inspiration from your proposal  to move the parser into the python lib. I'll do it in a new PR for clarity reasons.

**Comment by jcarpent** [comment]
I solved the problem by fixing a bug in EigenPy. I just open a new PR fixing the linkage problem (https://github.com/stack-of-tasks/eigenpy/pull/12). 
I will then open a new PR to fix the bug in Pinocchio after making a new release of EigenPy available on robotpkg.

**Pull request merged**
