### PR TITLE
Documentation 

### PR DESCRIPTION
**Pull request by drewhamiltonasdf**
A handful of updates to the documentation to get rid of deprecated python commands etc., a few grammar fixes, missing packages etc.

### CODE REVIEW

**Review by jcarpent — APPROVED** [review]

**Comment by jcarpent** [comment]
Thanks a lot @drewhamiltonasdf. This looks nice to me.
We can even go further by removing the use of `gepetto-gui` and using `meshcat` viewer instead.

**Comment by drewhamiltonasdf** [comment]
> Thanks a lot @drewhamiltonasdf. This looks nice to me. We can even go further by removing the use of `gepetto-gui` and using `meshcat` viewer instead.

No problem. I can go back to some of the earlier docs and update to MeshCat. Is gepetto-gui completely out of favor now? Also wondering if RobotWrapper.py is still the preferred URDF import method for custom URDF's? I'm going to have to dig into loading custom URDF packages eventually...

**Comment by jcarpent** [comment]
> Is gepetto-gui completely out of favor now?

Yes, it is no more the way to go. The generic approach relies on Meshcat which is multiplatform and more flexible.


> Also wondering if RobotWrapper.py is still the preferred URDF import method for custom URDF's?

It is a helper class. But for best performances, it is better to rely on a separate model and data, loaded via the custom URDF parser.

**Comment by jcarpent** [comment]
@drewhamiltonasdf A small suggestion, it would be better to squeeze your commits when they are related to the same change. You can use `git commit --amend` to amend the last commit with the latest modfications.

**Comment by drewhamiltonasdf** [comment]
> @drewhamiltonasdf A small suggestion, it would be better to squeeze your commits when they are related to the same change. You can use `git commit --amend` to amend the last commit with the latest modfications.

Will do going forward. Thanks!

**Comment by jcarpent** [comment]
I'm merging this first PR.
Thanks @drewhamiltonasdf for this nice and helpful contribution. We are looking forward to further doc improvements thanks to you.

**Pull request merged**
