### PR TITLE
Add changelog

### PR DESCRIPTION
**Pull request by jorisv**
Add a changelog inspired by https://keepachangelog.com/en/1.1.0/

### CODE REVIEW

**Comment by hrp2-14** [comment]
Hi ! This project doesn't usually accept pull requests on the main branch.
If this wasn't intentionnal, you can change the base branch of this PR to devel
(No need to close it for that). Best, a bot.

**Review by jcarpent — APPROVED** [review]

**Comment by jcarpent** [comment]
@jorisv Could you fix the issue with Codacy Static Code Analysis?

**Comment by jorisv** [comment]
> @jorisv Could you fix the issue with Codacy Static Code Analysis?

@jcarpent I prefer disable the check on CHANGELOG.md when the PR will be merged. Codacy want to have a different markdown style than the one proposed by keepachangelog.

**Review by nim65s — APPROVED** [review]
perfect, thanks !

**Pull request merged**
