### PR TITLE
ROS2 release support

### PR DESCRIPTION
**Pull request by wxmerkt**
WIP - testing branch to prepare a ROS2 release

### CODE REVIEW

**Comment by wxmerkt** [comment]
Okay, this will take a bit more time - I need to recursively release eigenpy and hpp-fcl first. Will update this PR once ready.

**Review by jcarpent — APPROVED** [review]
Thanks a lot @wxmerkt for the support of ROS-2.

**Comment by VladimirIvan** [comment]
@wxmerkt @jcarpent just wanted say I'm very much looking to the release in the ROS2 ecosystem. Let me know if I can help with the testing.

**Comment by jcarpent** [comment]
> @wxmerkt @jcarpent just wanted say I'm very much looking to the release in the ROS2 ecosystem. Let me know if I can help with the testing.

Thanks @VladimirIvan for your message. I'm finishing with #1723 and then I will provide a new release, hopefully today.

**Comment by wxmerkt** [comment]
With #1720 merged and the recent release of EigenPy and HPP-FCL into all ROS2 distributions, the CI should pass on this PR. Once it does, and once this one and #1723 are merged, we can make a release for ROS2.

**Comment by wxmerkt** [comment]
There appears to be an issue with the environment hooks and I will have to make amendments to eigenpy, hpp-fcl. and pinocchio or patch all releases. This will require some time, so my guess would be either late this week or next week for me to get to this [each distro has to be patched individually]

**Comment by jcarpent** [comment]
@wxmerkt Should I proceed to a release?

**Comment by nim65s** [comment]
Hi,

We now have issues with colcon:
```

after_run_target_test
  
  $ ( source /root/target_ws/install/setup.bash && cd /root/target_ws/build/pinocchio && make test; )
  /root/target_ws/install/setup.bash: line 11: COLCON_TRACE: unbound variable
'after_run_target_test' returned with code '1' after 0 min 0 sec

**Comment by wxmerkt** [comment]
I'm aware of the issue and waiting for my patched EigenPy/HPP-FCL to get merged upstream

**Comment by jcarpent** [comment]
Fantastic @wxmerkt. Thanks a lot.

**Pull request merged**
