### PR TITLE
cmake: do not check for Catkin when it is not needed

### PR DESCRIPTION
**Pull request by jcarpent**
This is for compilation issues in the CI process.
@wxmerkt Is it fine for you? Could you make your ROS building code compliant this new way of checking for Catkin?

### CODE REVIEW

**Comment by wxmerkt** [comment]
This likely is a regression for us and makes things more complicated. 

What is the compilation issue with a _quiet find_package_? Perhaps we can fix that issue instead.

Practically speaking, we could get rid off this catkin-type search entirely if Pinocchio uses the correct Python package path (i.e., whatever is standard on the distro and not forcing `site-packages` for all).

**Comment by jcarpent** [comment]
> Practically speaking, we could get rid off this catkin-type search entirely if Pinocchio uses the correct Python package path (i.e., whatever is standard on the distro and not forcing `site-packages` for all).

Ok. We can go towards this solution. Could you provide me more details?

**Comment by wxmerkt** [comment]
That would be ideal - we could totally go away with the catkin-wrappers then by using a simple `package.xml` and the jrl cmake modules.

The key here is to detect whether the system is debian-flavoured and set `PYTHON_DEB_LAYOUT` (exposed by jrl cmake modules in [2]) accordingly. [3] was attempting to automatically set it, but got blocked. It is now up to the individual user projects to add that logic (i.e., we'd need here, hpp-fcl, and eigenpy).

References:
1. https://github.com/jrl-umi3218/jrl-cmakemodules/issues/38, issue discussing incorrect Python-paths on debian-flavoured distributions.
2. https://github.com/jrl-umi3218/jrl-cmakemodules/pull/39, added Python-install location option
3. https://github.com/jrl-umi3218/jrl-cmakemodules/pull/47, would activate the correct flag automatically on a debian-based distribution - yet, blocked as it would affect too many downstream and suggested to handle on a per-project basis.
4. https://github.com/stack-of-tasks/pinocchio/issues/790, an ill-fated work-around suggestion to achieve the same thing.

**Comment by jcarpent** [comment]
@wxmerkt Thanks for this quick reply.
I would go towards #790, but the problem is that if catkin is present on the current machine, it means that Pinocchio will be installed in `dist-packages` while maybe this not intended by the user.

Is there a way to detect that Catkin is trying to build Pinocchio and then set on the respective flags?

**Comment by nim65s** [comment]
For the records:

```
Traceback (most recent call last):
File "/root/robotpkg/math/py-pinocchio/work.runner-7gqkM7SY-project-5-concurrent-35/pinocchio-2.1.2/catkin_generated/generate_cached_setup.py", line 20, in <module>
from catkin.environment_cache import generate_environment_script
ImportError: No module named catkin.environment_cache
CMake Error at /opt/ros/kinetic/share/catkin/cmake/safe_execute_process.cmake:11 (message):
execute_process(/usr/bin/python2.7
"/root/robotpkg/math/py-pinocchio/work.runner-7gqkM7SY-project-5-concurrent-35/pinocchio-2.1.2/catkin_generated/generate_cached_setup.py")
returned error code 1
Call Stack (most recent call first):
/opt/ros/kinetic/share/catkin/cmake/all.cmake:198 (safe_execute_process)
/opt/ros/kinetic/share/catkin/cmake/catkinConfig.cmake:20 (include)
CMakeLists.txt:93 (find_package)
```
In https://gepgitlab.laas.fr/stack-of-tasks/pinocchio/-/jobs/21970

I have no time to allow to this right now, sorry.

**Comment by jcarpent** [comment]
> For the records:
> 
> ```
> Traceback (most recent call last):
> File "/root/robotpkg/math/py-pinocchio/work.runner-7gqkM7SY-project-5-concurrent-35/pinocchio-2.1.2/catkin_generated/generate_cached_setup.py", line 20, in <module>
> from catkin.environment_cache import generate_environment_script
> ImportError: No module named catkin.environment_cache
> CMake Error at /opt/ros/kinetic/share/catkin/cmake/safe_execute_process.cmake:11 (message):
> execute_process(/usr/bin/python2.7
> "/root/robotpkg/math/py-pinocchio/work.runner-7gqkM7SY-project-5-concurrent-35/pinocchio-2.1.2/catkin_generated/generate_cached_setup.py")
> returned error code 1
> Call Stack (most recent call first):
> /opt/ros/kinetic/share/catkin/cmake/all.cmake:198 (safe_execute_process)
> /opt/ros/kinetic/share/catkin/cmake/catkinConfig.cmake:20 (include)
> CMakeLists.txt:93 (find_package)
> ```
> 
> In https://gepgitlab.laas.fr/stack-of-tasks/pinocchio/-/jobs/21970
> 
> I have no time to allow to this right now, sorry.

@nim65s I think we need to deactivate the search of catkin under robotpkg. This is easy to do.

**Comment by wxmerkt** [comment]
> I would go towards #790, but the problem is that if catkin is present on the current machine, it means that Pinocchio will be installed in dist-packages while maybe this not intended by the user.

Having thought more about it, I don't like the approach I initially proposed in #790 and the switch should be distro-dependent, not catkin-dependent. 
I'd like to remove all catkin-related modifications that are required workarounds from the CMakeLists. The correct way would be to follow the standard of the platform, and only do non-standard paths when absolutely necessary (i.e., if you choose to install always to `site-packages` in robotpkg, activate that flag only during robotpkg builds).

> Is there a way to detect that Catkin is trying to build Pinocchio and then set on the respective flags?

I tried and it got overcomplicated/wasn't possible. Ideally, resolving the Python package path situation would be best and would completely remove all catkin from the CMakeLists (which are a required workaround to deal with non-standard Python package paths).

My hunch to the error above is that Python35 does not have catkin installed - but CMake triggered it and forces `alias python=python3`. So the failures likely are only on Python3 builds.

**Comment by jmirabel** [comment]
>  (i.e., if you choose to install always to site-packages in robotpkg, activate that flag only during robotpkg builds).

That sounds good to me. I like the rule: *if the user did not specify anything, use the target OS settings*. 

Sadly, the t-OS (target OS), different from the b-OS (build OS) cannot be specified with CMake, can it ?
Does CMake assume that the t-OS is the b-OS ?
I believe the best way to answer the question @wxmerkt raised, and that has been regularly raised, is to find a good solution (and implementation in the JRL cmake module) to the problem:
*We need a way of knowing what the target OS is.*

Here are some suggestions:
- assume the t-OS is the b-OS, except if a particular CMake variable set the t-OS to something else.
- do target specific choices only if a CMake variable is set (otherwise, do not do any specific, not even for b-OS).

Maybe the good solution is to rely on `CMAKE_SYSTEM_NAME`: https://gitlab.kitware.com/cmake/community/wikis/doc/cmake/CrossCompiling
This requires us to write a `Platform/${CMAKE_SYSTEM_NAME}.cmake` for each platform we want to support. I believe **this is a hack** which may break things. Maybe a PROJECT_SYSTEM_NAME, with a file in the JRL cmake module, is better.


Any thoughts or suggestions ?

**Comment by wxmerkt** [comment]
Hi @jcarpent, sorry I have been out of the loop, what is the outcome of your conversations/discussions to package according to platform-standard unless deactivated?

**Comment by jcarpent** [comment]
@jcarpent I will provide a new PR for that. 
So, the idea is to make Pinocchio looking for the current OS policy as you mentioned with @jmirabel.
We will force the flag if needed when using robotpkg.
Is it fine for you?

**Comment by jcarpent** [comment]
I would even suggest to use Python directly to set `PYTHON_PACKAGES_DIR`. What do you think?

**Comment by wxmerkt** [comment]
Thank you very much for the change to cmake upstream, I made a comment there :-)

**Comment by jcarpent** [comment]
With the update on the jrl-cmake-modules, @wxmerkt do you think we can now remove the references to Catkin?

**Comment by wxmerkt** [comment]
Yes, I will make a series of pull requests to adjust. I want to first do a release to the ROS buildfarm of those so we can then adjust the dependent packages (but it will be a breaking changing of that version for some). E.g., eigenpy is currently (but will be removed because of the packaging issues) part of MoveIt and we also have dependent packages. 

Is it okay if I make the PR to remove it in a few days? And can we tag new releases with the updated cmake-module synced into hpp-fcl, eigenpy, and pinocchio?

**Comment by jcarpent** [comment]
Ok. I can make the PR for Pinocchio if you want?

**Comment by jcarpent** [comment]
with @lesteve, we will work soon on the packaging of Pinocchio inside `anaconda`. So we need to proceed as follows for eigenpy too.

**Comment by wxmerkt** [comment]
If you can sync the cmake submodule and tag releases, I will test the new ROS packaging (without the catkin-cmake wrapper) and test its impact

**Comment by wxmerkt** [comment]
Actually fine to remove catkin right now, we have released, tagged versions

**Comment by jcarpent** [comment]
> If you can sync the cmake submodule and tag releases, I will test the new ROS packaging (without the catkin-cmake wrapper) and test its impact

Ok sure. I've made a first proposal in #826.

**Pull request closed without merging**
