### PR TITLE
[Python] Fix usage of WITH_HPP_FCL_BINDINGS

### PR DESCRIPTION
**Pull request by jmirabel**
otherwise, `verbose = True` generates:
```python
AttributeError: 'module' object has no attribute 'WITH_HPP_FCL_BINDINGS'
```

### CODE REVIEW

**Comment by jmirabel** [comment]
CI failed to install a dependency because of a public key not available...

**Comment by gabrielebndn** [comment]
I think there is no need to change `pin.WITH_HPP_FCL` is fine, because this value is exposed from C++: 
https://github.com/stack-of-tasks/pinocchio/blob/4bc1b289713c46284e927064c24e845acdf29a62/bindings/python/utils/dependencies.cpp#L16-L21

Concerning `pin.WITH_HPP_FCL_BINDINGS`, you are right, that's a bug. But I think this quantity may have been rendered redundant and equivalent to `pin.WITH_HPP_FCL` from https://github.com/stack-of-tasks/pinocchio/pull/1084. Isn't that so?

**Comment by jmirabel** [comment]
> I think there is no need to change `pin.WITH_HPP_FCL`

There is indeed no need. I did it for homogeneity.

**Comment by jcarpent** [comment]
@jmirabel Apparently, your fix has failed on travis. In fact, I dot know how it can works and do not understand the error you got.

**Comment by jmirabel** [comment]
Again, I forgot that you pushed on my branch and overrode it by forced-pushing. I have re-committed the changes.

**Pull request merged**
