### PR TITLE
Correct compilation issue + warning removal for Win32 + msvc 142

### PR DESCRIPTION
**Pull request by francois-keith**

### CODE REVIEW

**Comment by hrp2-14** [comment]
Hi ! This project doesn't usually accept pull requests on master. If this wasn't intentionnal, you can change the base branch of this pull request to devel (No need to close it for that). Best, a bot.

**Review by jcarpent — APPROVED** [review]
Thanks for this contribution @francois-keith.
Do you think it would be possible to set various macros like:
- PINOCCHIO_COMPILER_DIAGNOSTIC_PUSH
- PINOCCHIO_COMPILER_DIAGNOSTIC_POP
- PINOCCHIO_COMPILER_DIAGNOSTIC_IGNORED_DEPRECECATED_DECLARATIONS

At least, it will allow us to reuse them without requiring a fix for Windows.

**Comment by francois-keith** [comment]
I'll have a look at it. Is there a particular place/header where those macros should be defined ?

**Comment by jcarpent** [comment]
> I'll have a look at it. Is there a particular place/header where those macros should be defined ?

In the macros.hpp file would be fine. Thanks for it.

**Review by jcarpent — APPROVED** [review]
Perfect. Thanks a lot @francois-keith.

**Pull request merged**
