### PR TITLE
bindings/python: fix bug related to eigenpy

### PR DESCRIPTION
**Pull request by jcarpent**
It seems that the desctructor invoked by eigenpy does not fit with the constructor invoked in Pinocchio.

This PR is related to #597

### CODE REVIEW

**Comment by jcarpent** [comment]
@gabrielebndn Can you tell me if this fix is working for you?

**Comment by gabrielebndn** [comment]
Everything is working now.
I am surprised `exp3` works correctly.
If you merge this PR, I will update #597 so you can merge it too.

**Comment by jcarpent** [comment]
OK. Thanks for your quick feedback!

**Comment by gabrielebndn** [comment]
Thanks to you for your quick solution!

**Pull request merged**
