### PR TITLE
Fix constructor for Data, related to #970

### PR DESCRIPTION
**Pull request by jcarpent**
@Leph I've fixed your issue ;)

### CODE REVIEW

**Comment by Leph** [comment]
@jcarpent, thank you very much.

**Comment by gabrielebndn** [comment]
I have this problem too. My unit tests are failing because of this. Could you make a new release including this fix? Possibly on apt too? @jcarpent? @nim65s?

**Comment by gabrielebndn** [comment]
This is kind of important, because although no actual code appears to be broken in Release mode (it is an assertion which is failing), I am not sure of what might happen if the precondition is not met. So, I would prefer this to be fixed as soon as possible.

**Comment by cmastalli** [comment]
@jcarpenter this things to be the error in Crocoddyl reported in

https://github.com/loco-3d/crocoddyl/issues/645

**Pull request merged**
