### PR TITLE
Add missing dependencies into pkg-config

### PR DESCRIPTION
**Pull request by jorisv**
This PR add the following libraries into the pkg-config file (when built with the right option) :

- pinocchio_parsers
- pinocchio_collision
- pinocchio_extra
- pinocchio_casadi
- pinocchio_cppad
- pinocchio_cppadcg

Add missing defines.

### CODE REVIEW

**Comment by jorisv** [comment]
Fix #2321

**Comment by jorisv** [comment]
CI is broken because of https://github.com/conda-forge/qhull-feedstock/pull/19

**Review by nim65s — DISMISSED** [review]
LGTM, but maybe we could add code from #2321 in CI ?
I guess if this was broken for so long, it shows that none of us use pkg-config.

**Comment by jorisv** [comment]
@nim65s We can maybe modify `unittest/packaging/pkgconfig` to use more dependencies.

**Comment by jorisv** [comment]
@nim65s I have added a test for pinocchio_parsers + pkgconfig.

It's not relevant to test cppad, casadi, cppadcg and collision because they only contains template instantiation.

**Review by jcarpent — APPROVED** [review]

**Pull request merged**
