### PR TITLE
Sync submodule CMake

### PR DESCRIPTION
**Pull request by jcarpent**

### CODE REVIEW

**Comment by jcarpent** [comment]
@wxmerkt Any hint why melodic is not able to find hpp-fcl? Thanks in advance for your feedback.

**Comment by wxmerkt** [comment]
We need a new release of HPP-FCL with the fixed CMake (current devel with updated cmake submodule) and then I can run a release to have it available on Melodic as well

**Comment by jcarpent** [comment]
OK. Perfect. I will do that now then. Thanks a lot for the quick feedback. Very helpful

**Comment by wxmerkt** [comment]
@jcarpent Thank you for the swift release. The problem should be resolved now, I've restarted the build

**Pull request merged**
