### PR TITLE
Move python bindings to a dedicated directory + split bindings in several .o files

### PR DESCRIPTION
**Pull request by jcarpent**
Related to #230 and #247.

### CODE REVIEW

**Comment by jcarpent** [comment]
I think the time is disappointing. I tried to create several .o for the python bindings and the compilation reached 6:49 min against 2:30 min. I think the change is not necessary at all.

**Comment by nmansard** [comment]
Sorry, but we cannot track the modifs in this PR because git unproperly tracked the file moves. Could you redo it with proper tracking?

**Comment by jcarpent** [comment]
I do not get your comment. The first commit `[CMake] Move python to a dedicated directory` follows well the `git mv`

**Comment by nmansard** [comment]
Ok. That's the expose algorithm that was split.

**Comment by jcarpent** [comment]
Just updated and it passed. I will now merge.

**Pull request merged**
