### PR TITLE
Split test files and update submodule CMake

### PR DESCRIPTION
**Pull request by jcarpent**

### CODE REVIEW

**Comment by jcarpent** [comment]
Fixing #1096.

**Comment by wxmerkt** [comment]
Awesome! Did you check if that reduces the memory to less than 2GB?

**Comment by jcarpent** [comment]
No, but for sure it will reduce the overhead. The other test files contain larger compilations units ;)

**Comment by wxmerkt** [comment]
Ok, just checking if it was fully fixing/closing the mentioned issue :-)

**Pull request merged**
