### PR TITLE
[Model] Fix appendModel for parallel joints at the base

### PR DESCRIPTION
**Pull request by MegMll**
Solves [#2293 ](https://github.com/stack-of-tasks/pinocchio/issues/2293)

When joints at the base are in parallel, the transformation between modelA and modelB was applied only the first joint of the list, whereas it should be applied on all joints whose parent is the base of modelB.

### CODE REVIEW

**Review by jcarpent — APPROVED** [review]
Thanks a lot @MegMll for fixing this issue

**Comment by jcarpent** [comment]
@MegMll Could you add simple unit tests to check this fix?

**Comment by HarisCavkic** [comment]
Hello,

We are currently using pinocchio with pip(linux/Mac) and with conda-forge(Win). When can we expect updates for this fix?

Kind regards,
Haris

**Comment by jorisv** [comment]
We will probably make a new Pinocchio release next week. The conda-forge package should be available one day after the release.

**Pull request merged**
