### PR TITLE
Kinetic and potential energy regressors

### PR DESCRIPTION
**Pull request by lvjonok**
Hello Pinocchio team!

I am pleased to use your library and apply it for system identification purposes. I have found much useful `jointTorqueRegressor` and wanted to contribute by implementing `kineticEnergyRegressor` and `potentialEnergyRegressor`.These functions are alike `jointTorqueRegressor` show a linear connection from dynamical parameters to dynamical quantity.

I have added tests and documentation up to my capability. 

Please let me know your thoughts, I am open for modifications and there are more ideas on possible contribution I am willing to implement later.

### CODE REVIEW

**Comment by jcarpent** [comment]
Thanks a lot @lvjonok for contributing to Pinocchio.
We will proceed to a review of your code and will be happy to have it in Pinocchio.

Thanks again for using and contributing to Pinocchio.

**Comment by lvjonok** [comment]
I am having a growing concern about the naming. Maybe `jointKineticEnergyRegressor` and `jointPotentialEnergyRegressor` would be better names for the functions because `JointTorqueRegressor` has the similar naming idea behind.

**Comment by jcarpent** [comment]
@lvjonok I've provided some slight change to your initial PR.
Could you have a look?

**Comment by lvjonok** [comment]
> @lvjonok I've provided some slight change to your initial PR. Could you have a look?

Thanks for the update! The changes look great. Could you please change my affiliation information before finalizing the PR? I would rather have it like this:

[Lev Kozlov](https://github.com/lvjonok): Kinetic and potential energy regressors

**Pull request merged**
