### PR TITLE
[Doc] Add remarkable identities for Jlog6

### PR DESCRIPTION
**Pull request by jmirabel**
When rendered, this adds to doc of `Jlog6`:

image

### CODE REVIEW

**Review by jcarpent — CHANGES_REQUESTED** [review]
You should change x which stands for the cross operator when working with Lie algebra

**Comment by jmirabel** [comment]
You are correct. How should I mark the multiply. I think a mere space not very explicit.

**Comment by jcarpent** [comment]
I would suggest something like:
log_6(exp_6(a)exp_6(b)) with X_b = Ad_{exp_6(b)}^-1

**Comment by jmirabel** [comment]
I cannot write it with `exp_6` as I would have to write the derivatives wrt to `exp_6(a)` and not `a`. Or I did not understand what you meant. 

Here is what I came up after some re-writing.
image

**Comment by jcarpent** [comment]
Could you use small letters for so(3) elements ? And Ad_A for X_A?

**Comment by jmirabel** [comment]
image

**Review by jcarpent — APPROVED** [review]
Thanks a lot.

**Comment by jmirabel** [comment]
Sorry for the misunderstanding. I wanted to come to an agreement before pushing to avoid useless CI. What you merge is the original change. I'll open a new PR.

**Pull request merged**
