### PR TITLE
Simplify RPY code

### PR DESCRIPTION
**Pull request by jcarpent**
The idea is to rely on Eigen's code which seems to be more numerically robust.
As future work, it would be necessary to adapt this code to handle Autodiff support.

### CODE REVIEW

**Comment by traversaro** [comment]
Did you checked the ranges of the angles returned by Eigen's [`eulerAngles`](https://eigen.tuxfamily.org/dox/group__Geometry__Module.html#title20)? 

We tried using it in the past, but the fact that one of the angles returned values in `[0, pi]` makes it quite problematic, as most of the code using RPY's have the implicit assumption that there are no discontinuities around the identity rotation (that corresponds to rpy = (0, 0, 0) ).

Related  iDynTree issue: 
* https://github.com/robotology/idyntree/pull/504

**Comment by gabrielebndn** [comment]
Please don't do this. I wrote this function. The point of _not_ using `eulerAngles` was that `eulerAngles` does not return the angles in the correct range that one would expect for RPY, i.e. [-pi,pi], [-pi/2,pi/2], [-pi,pi]. Otherwise, there would be no need of this function, just using `eulerAngles` is simple enough :)

**Comment by gabrielebndn** [comment]
The documentation clearly states:
```
    /// The angles are guaranteed to be in the ranges \f$r\in[-\pi,\pi]\f$
    /// \f$p\in[-\frac{\pi}{2},\frac{\pi}{2}]\f$ \f$y\in[-\pi,\pi]\f$.
```
with the new changes, this is not true any more

**Comment by gabrielebndn** [comment]
Actually, it would be a good idea to add a unit test to check that the angles are in the correct range. I should have done it when I added this function

**Comment by jcarpent** [comment]
@traversaro Thanks a lot for the pointer. I will address this issue by employing something similar to what it has been done in Drake.

**Comment by jcarpent** [comment]
@gabrielebndn The current implementation is not safe at all in terms of numerical stability and the necessity of thresholding some values for the roll angle. It would be better to provide something which is more robust.

**Comment by gabrielebndn** [comment]
One alternative to writing a custom formula is to use the unsupported `EulerAngles` module, which allows to explicitly select the output range. I did not want to do it, but if you prefer, I can make a new PR myself

**Comment by gabrielebndn** [comment]
Although I do not now since when that module is supported, and I have no idea how good it is

**Comment by jcarpent** [comment]
OK. @gabrielebndn Please push on this PR by copy-pasting the code from the unsupported folder. Do you have time to do it now?

**Comment by gabrielebndn** [comment]
@jcarpent the main point of having this function was for visualization. If the angles are not in the correct ranges, it is difficult to understand what the 3D orientation looks like. E.g. [0, -pi/100, 0], which is really close to identity, becomes something completely incomprehensible for a human reader. One may therefore put a warning in the documentation about this. But I think that any robustifying solution should guarantee the correct range

**Comment by gabrielebndn** [comment]
> OK. @gabrielebndn Please push on this PR by copy-pasting the code from the unsupported folder. Do you have time to do it now?

I can do it later today. This was a long day, and I still have to have lunch :)

**Comment by jcarpent** [comment]
> I can do it later today. This was a long day, and I still have to have lunch :)

OK. Perfect. I let you manage the rest then. Thank you very much and enjoy your meal!

**Comment by gabrielebndn** [comment]
@jcarpent, in the end I chose a different implementation. I am using `eulerAngles`, but then I modify the result according to the value of the pitch. Let me know if this is ok for you

I modified your unit test: now I am checking that the angles are exactly the ones used to compute the matrix. I am not super happy about it because in principle it can fail, if a singularity is hit during the random generation. If you wish, we can go back to a test more similar to your one, but that also explicitly checks for the angle range

**Comment by gabrielebndn** [comment]
CI does not pass because the linter does not like Eigen's comma operator. Is this normal? @jmirabel?

**Comment by gabrielebndn** [comment]
BTW, I have just seen the link by @traversaro and I wish I had seen it earlier. @jcarpent, what about this code? Should we copy this or keep my solution?

https://github.com/prajval10/idyntree/blob/2a2e47678cff17690b45981b1961360006a3aafc/src/core/src/Rotation.cpp#L302-L330

**Comment by jmirabel** [comment]
> CI does not pass because the linter does not like Eigen's comma operator. Is this normal? @jmirabel?

I saw them. I think they are false positive. The only relevant thread I could find is https://sourceforge.net/p/cppcheck/discussion/development/thread/1b66df674f/

**Comment by jmirabel** [comment]
I disabled "Redundant code: Found a statement that begins with type constant." for cppcheck. Those error should disappear.

**Comment by traversaro** [comment]
> 
> 
> BTW, I have just seen the link by @traversaro and I wish I had seen it earlier. @jcarpent, what about this code? Should we copy this or keep my solution?
> 
> https://github.com/prajval10/idyntree/blob/2a2e47678cff17690b45981b1961360006a3aafc/src/core/src/Rotation.cpp#L302-L330

For reference, I checked that method switch away from `Eigen::eulerAngles` to that version in https://github.com/robotology/idyntree/pull/156 and I think that version had been inspired from [`yarp::math::dcm2rpy`](https://github.com/robotology/yarp/blob/v3.3.2/src/libYARP_math/src/yarp/math/math.cpp#L777) that I think was inspired on some kind of MATLAB function back in time. 

In any case, if you are interested in any particular property of the representation (for example continuity of some kind, or being well-defined in the sense that rotMat --> rpy ---> rotMat is an identity even close to a singularity) I suggest not to trust any random implementation you find around, but rather add a specific test to validate the property you are interested in. 

In particular for RotMat --> RPY functions, testing over a few random rotations is topically not enough to make sure that everything works fine near singularities and at boundaries of the subset of ℝ³ selected as an image as the function, as it is high probable that the random rotations do not fall near this special points. It is better to also test near "special" points as done in this PR in https://github.com/stack-of-tasks/pinocchio/pull/1158/files#diff-389deb81223b9973b368252842c0015cR61 and in https://github.com/ros/urdfdom/pull/67/files#diff-9ae31c7b731c779d312dd54b8e78c96fR89 .

**Comment by gabrielebndn** [comment]
@traversaro, you are absolutely right. In this PR I am explicitly checking at singularities

**Pull request merged**
